//<debug>

this.ExtBootstrapData = {
    "nameToAliasesMap":{
        "Ext.AbstractComponent":[],
        "Ext.AbstractManager":[],
        "Ext.ActionSheet":["widget.actionsheet"
        ],
        "Ext.Ajax":[],
        "Ext.Anim":[],
        "Ext.Audio":["widget.audio"
        ],
        "Ext.Button":["widget.button"
        ],
        "Ext.Component":["widget.component"
        ],
        "Ext.ComponentManager":[],
        "Ext.ComponentQuery":[],
        "Ext.Container":["widget.container"
        ],
        "Ext.Decorator":[],
        "Ext.Evented":[],
        "Ext.Img":["widget.image",
            "widget.img"
        ],
        "Ext.ItemCollection":[],
        "Ext.Label":["widget.label"
        ],
        "Ext.LoadMask":["widget.loadmask"
        ],
        "Ext.Map":["widget.map"
        ],
        "Ext.Mask":["widget.mask"
        ],
        "Ext.Media":["widget.media"
        ],
        "Ext.MessageBox":[],
        "Ext.Panel":["widget.panel"
        ],
        "Ext.SegmentedButton":["widget.segmentedbutton"
        ],
        "Ext.Sheet":["widget.sheet"
        ],
        "Ext.Spacer":["widget.spacer"
        ],
        "Ext.TaskQueue":[],
        "Ext.Template":[],
        "Ext.Title":["widget.title"
        ],
        "Ext.TitleBar":["widget.titlebar"
        ],
        "Ext.Toolbar":["widget.toolbar"
        ],
        "Ext.Video":["widget.video"
        ],
        "Ext.XTemplate":[],
        "Ext.XTemplateCompiler":[],
        "Ext.XTemplateParser":[],
        "Ext.app.Action":[],
        "Ext.app.Application":[],
        "Ext.app.Controller":[],
        "Ext.app.History":[],
        "Ext.app.Profile":[],
        "Ext.app.Route":[],
        "Ext.app.Router":[],
        "Ext.behavior.Behavior":[],
        "Ext.behavior.Draggable":[],
        "Ext.behavior.Scrollable":[],
        "Ext.behavior.Translatable":[],
        "Ext.carousel.Carousel":["widget.carousel"
        ],
        "Ext.carousel.Indicator":["widget.carouselindicator"
        ],
        "Ext.carousel.Infinite":[],
        "Ext.carousel.Item":[],
        "Ext.chart.AbstractChart":[],
        "Ext.chart.CartesianChart":["widget.chart",
            "Ext.chart.Chart"
        ],
        "Ext.chart.PolarChart":["widget.polar"
        ],
        "Ext.chart.Shape":[],
        "Ext.chart.SpaceFillingChart":["widget.spaceFilling"
        ],
        "Ext.chart.axis.Abstract":["widget.axis"
        ],
        "Ext.chart.axis.Axis":[],
        "Ext.chart.axis.Category":["axis.category"
        ],
        "Ext.chart.axis.Gauge":[],
        "Ext.chart.axis.Numeric":["axis.numeric"
        ],
        "Ext.chart.axis.Radial":[],
        "Ext.chart.axis.Time":["axis.time"
        ],
        "Ext.chart.axis.layout.CombineDuplicate":["axisLayout.combineDuplicate"
        ],
        "Ext.chart.axis.layout.Continuous":["axisLayout.continuous"
        ],
        "Ext.chart.axis.layout.Discrete":["axisLayout.discrete"
        ],
        "Ext.chart.axis.layout.Layout":[],
        "Ext.chart.axis.segmenter.Names":["segmenter.names"
        ],
        "Ext.chart.axis.segmenter.Numeric":["segmenter.numeric"
        ],
        "Ext.chart.axis.segmenter.Segmenter":[],
        "Ext.chart.axis.segmenter.Time":["segmenter.time"
        ],
        "Ext.chart.axis.sprite.Axis":[],
        "Ext.chart.interactions.Abstract":["widget.interaction"
        ],
        "Ext.chart.interactions.ItemCompare":["interaction.itemcompare"
        ],
        "Ext.chart.interactions.ItemHighlight":["interaction.itemhighlight"
        ],
        "Ext.chart.interactions.ItemInfo":["interaction.iteminfo"
        ],
        "Ext.chart.interactions.PanZoom":["interaction.panzoom"
        ],
        "Ext.chart.interactions.PieGrouping":["interaction.piegrouping"
        ],
        "Ext.chart.interactions.Reset":["interaction.reset"
        ],
        "Ext.chart.interactions.Rotate":["interaction.rotate"
        ],
        "Ext.chart.interactions.RotatePie3D":["interaction.rotatePie3d"
        ],
        "Ext.chart.interactions.ToggleStacked":["interaction.togglestacked"
        ],
        "Ext.chart.legend.View":[],
        "Ext.chart.series.AbstractRadial":[],
        "Ext.chart.series.AbstractSpaceFilling":[],
        "Ext.chart.series.Area":["series.area"
        ],
        "Ext.chart.series.Bar":["series.bar"
        ],
        "Ext.chart.series.CandleStick":["series.candlestick"
        ],
        "Ext.chart.series.Cartesian":[],
        "Ext.chart.series.Column":["series.column"
        ],
        "Ext.chart.series.Gauge":[],
        "Ext.chart.series.Icicle":[],
        "Ext.chart.series.ItemEvents":[],
        "Ext.chart.series.Line":["series.line"
        ],
        "Ext.chart.series.Pie":["series.pie"
        ],
        "Ext.chart.series.Pie3D":["series.pie3d"
        ],
        "Ext.chart.series.Polar":[],
        "Ext.chart.series.Radar":["series.radar"
        ],
        "Ext.chart.series.Scatter":["series.scatter"
        ],
        "Ext.chart.series.Series":[],
        "Ext.chart.series.StackedCartesian":[],
        "Ext.chart.series.Sunburst":[],
        "Ext.chart.series.Treemap":[],
        "Ext.chart.series.Wordmap":[],
        "Ext.chart.series.sprite.AbstractRadial":[],
        "Ext.chart.series.sprite.Aggregative":[],
        "Ext.chart.series.sprite.Area":["sprite.areaSeries"
        ],
        "Ext.chart.series.sprite.Bar":["sprite.barSeries"
        ],
        "Ext.chart.series.sprite.CandleStick":["sprite.candlestickSeries"
        ],
        "Ext.chart.series.sprite.Cartesian":[],
        "Ext.chart.series.sprite.Column":["sprite.columnSeries"
        ],
        "Ext.chart.series.sprite.Line":["sprite.lineSeries"
        ],
        "Ext.chart.series.sprite.Markers":[],
        "Ext.chart.series.sprite.Pie3DPart":["sprite.pie3dPart"
        ],
        "Ext.chart.series.sprite.Polar":[],
        "Ext.chart.series.sprite.Radar":["sprite.radar"
        ],
        "Ext.chart.series.sprite.Scatter":["sprite.scatterSeries"
        ],
        "Ext.chart.series.sprite.StackedCartesian":[],
        "Ext.chart.theme.Base":[],
        "Ext.chart.theme.CalloutStyle":[],
        "Ext.chart.theme.EvenStyle":[],
        "Ext.chart.theme.GridStyle":[],
        "Ext.chart.theme.HighlightStyle":[],
        "Ext.chart.theme.LabelStyle":[],
        "Ext.chart.theme.MarkerStyle":[],
        "Ext.chart.theme.OddStyle":[],
        "Ext.chart.theme.Style":[],
        "Ext.chart.theme.Theme":[],
        "Ext.chart.theme.TitleStyle":[],
        "Ext.data.ArrayStore":["store.array"
        ],
        "Ext.data.Batch":[],
        "Ext.data.Connection":[],
        "Ext.data.DirectStore":["store.direct"
        ],
        "Ext.data.Error":[],
        "Ext.data.Errors":[],
        "Ext.data.Field":["data.field"
        ],
        "Ext.data.JsonP":[],
        "Ext.data.JsonStore":["store.json"
        ],
        "Ext.data.Model":[],
        "Ext.data.ModelManager":[],
        "Ext.data.NodeInterface":[],
        "Ext.data.NodeStore":["store.node"
        ],
        "Ext.data.Operation":[],
        "Ext.data.Request":[],
        "Ext.data.ResultSet":[],
        "Ext.data.SortTypes":[],
        "Ext.data.Store":["store.store"
        ],
        "Ext.data.StoreManager":[],
        "Ext.data.TreeStore":["store.tree"
        ],
        "Ext.data.Types":[],
        "Ext.data.Validations":[],
        "Ext.data.association.Association":[],
        "Ext.data.association.BelongsTo":["association.belongsto"
        ],
        "Ext.data.association.HasMany":["association.hasmany"
        ],
        "Ext.data.association.HasOne":["association.hasone"
        ],
        "Ext.data.identifier.Sequential":["data.identifier.sequential"
        ],
        "Ext.data.identifier.Simple":["data.identifier.simple"
        ],
        "Ext.data.identifier.Uuid":["data.identifier.uuid"
        ],
        "Ext.data.proxy.Ajax":["proxy.ajax"
        ],
        "Ext.data.proxy.Client":[],
        "Ext.data.proxy.Direct":["proxy.direct"
        ],
        "Ext.data.proxy.JsonP":["proxy.jsonp",
            "proxy.scripttag"
        ],
        "Ext.data.proxy.LocalStorage":["proxy.localstorage"
        ],
        "Ext.data.proxy.Memory":["proxy.memory"
        ],
        "Ext.data.proxy.Proxy":["proxy.proxy"
        ],
        "Ext.data.proxy.Rest":["proxy.rest"
        ],
        "Ext.data.proxy.Server":["proxy.server"
        ],
        "Ext.data.proxy.SessionStorage":["proxy.sessionstorage"
        ],
        "Ext.data.proxy.SQL":["proxy.sql"
        ],
        "Ext.data.proxy.WebStorage":[],
        "Ext.data.reader.Array":["reader.array"
        ],
        "Ext.data.reader.Json":["reader.json"
        ],
        "Ext.data.reader.Reader":[],
        "Ext.data.reader.Xml":["reader.xml"
        ],
        "Ext.data.writer.Json":["writer.json"
        ],
        "Ext.data.writer.Writer":["writer.base"
        ],
        "Ext.data.writer.Xml":["writer.xml"
        ],
        "Ext.dataview.DataView":["widget.dataview"
        ],
        "Ext.dataview.IndexBar":[],
        "Ext.dataview.List":["widget.list"
        ],
        "Ext.dataview.ListItemHeader":["widget.listitemheader"
        ],
        "Ext.dataview.NestedList":["widget.nestedlist"
        ],
        "Ext.dataview.component.Container":[],
        "Ext.dataview.component.DataItem":["widget.dataitem"
        ],
        "Ext.dataview.component.Infinite":[],
        "Ext.dataview.element.Container":[],
        "Ext.dataview.element.List":[],
        "Ext.direct.Event":["direct.event"
        ],
        "Ext.direct.ExceptionEvent":["direct.exception"
        ],
        "Ext.direct.JsonProvider":["direct.jsonprovider"
        ],
        "Ext.direct.Manager":[],
        "Ext.direct.PollingProvider":["direct.pollingprovider"
        ],
        "Ext.direct.Provider":["direct.provider"
        ],
        "Ext.direct.RemotingEvent":["direct.rpc"
        ],
        "Ext.direct.RemotingMethod":[],
        "Ext.direct.RemotingProvider":["direct.remotingprovider"
        ],
        "Ext.direct.Transaction":["direct.transaction"
        ],
        "Ext.dom.CompositeElement":[],
        "Ext.dom.CompositeElementLite":[],
        "Ext.dom.Element":["widget.element"
        ],
        "Ext.dom.Helper":[],
        "Ext.dom.Query":[],
        "Ext.draw.Color":[],
        "Ext.draw.Component":["widget.draw"
        ],
        "Ext.draw.Draw":[],
        "Ext.draw.Group":[],
        "Ext.draw.LimitedCache":[],
        "Ext.draw.Matrix":[],
        "Ext.draw.RMQ":[],
        "Ext.draw.SegmentTree":[],
        "Ext.draw.Surface":["widget.surface"
        ],
        "Ext.draw.TextMeasurer":[],
        "Ext.draw.engine.Canvas":[],
        "Ext.draw.engine.ImageExporter":[],
        "Ext.draw.engine.Svg":[],
        "Ext.draw.engine.SvgExporter":[],
        "Ext.draw.fx.Abstract":[],
        "Ext.draw.fx.Frame":[],
        "Ext.draw.fx.Parser":[],
        "Ext.draw.fx.Queue":[],
        "Ext.draw.fx.TimingFunctions":[],
        "Ext.draw.gradient.Gradient":[],
        "Ext.draw.gradient.Linear":[],
        "Ext.draw.gradient.Radial":[],
        "Ext.draw.modifier.Animation":["modifier.animation"
        ],
        "Ext.draw.modifier.Highlight":["modifier.highlight"
        ],
        "Ext.draw.modifier.Modifier":[],
        "Ext.draw.modifier.Target":["modifier.target"
        ],
        "Ext.draw.path.Path":[],
        "Ext.draw.sprite.Arc":["sprite.arc"
        ],
        "Ext.draw.sprite.AttributeDefinition":[],
        "Ext.draw.sprite.AttributeParser":[],
        "Ext.draw.sprite.Circle":["sprite.circle"
        ],
        "Ext.draw.sprite.Composite":["sprite.composite"
        ],
        "Ext.draw.sprite.Ellipse":["sprite.ellipse"
        ],
        "Ext.draw.sprite.EllipticalArc":["sprite.ellipticalArc"
        ],
        "Ext.draw.sprite.Image":["sprite.image"
        ],
        "Ext.draw.sprite.Instancing":["sprite.instancing"
        ],
        "Ext.draw.sprite.Path":["sprite.path"
        ],
        "Ext.draw.sprite.Rect":["sprite.rect"
        ],
        "Ext.draw.sprite.Sector":["sprite.sector"
        ],
        "Ext.draw.sprite.Sprite":[],
        "Ext.draw.sprite.Text":["sprite.text"
        ],
        "Ext.env.Browser":[],
        "Ext.env.Feature":[],
        "Ext.env.OS":[],
        "Ext.event.Controller":[],
        "Ext.event.Dispatcher":[],
        "Ext.event.Dom":[],
        "Ext.event.Event":[],
        "Ext.event.ListenerStack":[],
        "Ext.event.Touch":[],
        "Ext.event.publisher.ComponentDelegation":[],
        "Ext.event.publisher.ComponentPaint":[],
        "Ext.event.publisher.ComponentSize":[],
        "Ext.event.publisher.Dom":[],
        "Ext.event.publisher.ElementPaint":[],
        "Ext.event.publisher.ElementSize":[],
        "Ext.event.publisher.Publisher":[],
        "Ext.event.publisher.TouchGesture":[],
        "Ext.event.recognizer.DoubleTap":[],
        "Ext.event.recognizer.Drag":[],
        "Ext.event.recognizer.HorizontalSwipe":[],
        "Ext.event.recognizer.LongPress":[],
        "Ext.event.recognizer.MultiTouch":[],
        "Ext.event.recognizer.Pinch":[],
        "Ext.event.recognizer.Recognizer":[],
        "Ext.event.recognizer.Rotate":[],
        "Ext.event.recognizer.SingleTouch":[],
        "Ext.event.recognizer.Tap":[],
        "Ext.event.recognizer.Touch":[],
        "Ext.field.Checkbox":["widget.checkboxfield"
        ],
        "Ext.field.DatePicker":["widget.datepickerfield"
        ],
        "Ext.field.Email":["widget.emailfield"
        ],
        "Ext.field.Field":["widget.field"
        ],
        "Ext.field.Hidden":["widget.hiddenfield"
        ],
        "Ext.field.Input":["widget.input"
        ],
        "Ext.field.Number":["widget.numberfield"
        ],
        "Ext.field.Password":["widget.passwordfield"
        ],
        "Ext.field.Radio":["widget.radiofield"
        ],
        "Ext.field.Search":["widget.searchfield"
        ],
        "Ext.field.Select":["widget.selectfield"
        ],
        "Ext.field.Slider":["widget.sliderfield"
        ],
        "Ext.field.Spinner":["widget.spinnerfield"
        ],
        "Ext.field.Text":["widget.textfield"
        ],
        "Ext.field.TextArea":["widget.textareafield"
        ],
        "Ext.field.TextAreaInput":["widget.textareainput"
        ],
        "Ext.field.Toggle":["widget.togglefield"
        ],
        "Ext.field.Url":["widget.urlfield"
        ],
        "Ext.form.FieldSet":["widget.fieldset"
        ],
        "Ext.form.Panel":["widget.formpanel"
        ],
        "Ext.fx.Animation":[],
        "Ext.fx.Easing":[],
        "Ext.fx.Runner":[],
        "Ext.fx.State":[],
        "Ext.fx.animation.Abstract":[],
        "Ext.fx.animation.Cube":["animation.cube"
        ],
        "Ext.fx.animation.Fade":["animation.fade",
            "animation.fadeIn"
        ],
        "Ext.fx.animation.FadeOut":["animation.fadeOut"
        ],
        "Ext.fx.animation.Flip":["animation.flip"
        ],
        "Ext.fx.animation.Pop":["animation.pop",
            "animation.popIn"
        ],
        "Ext.fx.animation.PopOut":["animation.popOut"
        ],
        "Ext.fx.animation.Slide":["animation.slide",
            "animation.slideIn"
        ],
        "Ext.fx.animation.SlideOut":["animation.slideOut"
        ],
        "Ext.fx.easing.Abstract":[],
        "Ext.fx.easing.Bounce":[],
        "Ext.fx.easing.BoundMomentum":[],
        "Ext.fx.easing.EaseIn":["easing.ease-in"
        ],
        "Ext.fx.easing.EaseOut":["easing.ease-out"
        ],
        "Ext.fx.easing.Linear":["easing.linear"
        ],
        "Ext.fx.easing.Momentum":[],
        "Ext.fx.layout.Card":[],
        "Ext.fx.layout.card.Abstract":[],
        "Ext.fx.layout.card.Cover":["fx.layout.card.cover"
        ],
        "Ext.fx.layout.card.Cube":["fx.layout.card.cube"
        ],
        "Ext.fx.layout.card.Fade":["fx.layout.card.fade"
        ],
        "Ext.fx.layout.card.Flip":["fx.layout.card.flip"
        ],
        "Ext.fx.layout.card.Pop":["fx.layout.card.pop"
        ],
        "Ext.fx.layout.card.Reveal":["fx.layout.card.reveal"
        ],
        "Ext.fx.layout.card.Scroll":["fx.layout.card.scroll"
        ],
        "Ext.fx.layout.card.Slide":["fx.layout.card.slide"
        ],
        "Ext.fx.layout.card.Style":[],
        "Ext.fx.runner.Css":[],
        "Ext.fx.runner.CssTransition":[],
        "Ext.layout.Abstract":[],
        "Ext.layout.Box":["layout.tablebox"
        ],
        "Ext.layout.Card":["layout.card"
        ],
        "Ext.layout.Default":["layout.default"
        ],
        "Ext.layout.Fit":["layout.fit"
        ],
        "Ext.layout.FlexBox":["layout.box"
        ],
        "Ext.layout.Float":["layout.float"
        ],
        "Ext.layout.HBox":["layout.hbox"
        ],
        "Ext.layout.VBox":["layout.vbox"
        ],
        "Ext.layout.wrapper.BoxDock":[],
        "Ext.layout.wrapper.Dock":[],
        "Ext.layout.wrapper.Inner":[],
        "Ext.log.Base":[],
        "Ext.log.Logger":[],
        "Ext.log.filter.Filter":[],
        "Ext.log.filter.Priority":[],
        "Ext.log.formatter.Default":[],
        "Ext.log.formatter.Formatter":[],
        "Ext.log.formatter.Identity":[],
        "Ext.log.writer.Console":[],
        "Ext.log.writer.DocumentTitle":[],
        "Ext.log.writer.Remote":[],
        "Ext.log.writer.Writer":[],
        "Ext.mixin.Bindable":[],
        "Ext.mixin.Filterable":[],
        "Ext.mixin.Identifiable":[],
        "Ext.mixin.Mixin":[],
        "Ext.mixin.Observable":[],
        "Ext.mixin.Selectable":[],
        "Ext.mixin.Sortable":[],
        "Ext.mixin.Templatable":[],
        "Ext.mixin.Traversable":[],
        "Ext.navigation.Bar":[],
        "Ext.navigation.View":["widget.navigationview"
        ],
        "Ext.picker.Date":["widget.datepicker"
        ],
        "Ext.picker.Picker":["widget.picker"
        ],
        "Ext.picker.Slot":["widget.pickerslot"
        ],
        "Ext.plugin.ListPaging":["plugin.listpaging"
        ],
        "Ext.plugin.PullRefresh":["plugin.pullrefresh"
        ],
        "Ext.scroll.Indicator":[],
        "Ext.scroll.Scroller":[],
        "Ext.scroll.View":[],
        "Ext.scroll.indicator.Abstract":[],
        "Ext.scroll.indicator.CssTransform":[],
        "Ext.scroll.indicator.Default":[],
        "Ext.scroll.indicator.ScrollPosition":[],
        "Ext.slider.Slider":["widget.slider"
        ],
        "Ext.slider.Thumb":["widget.thumb"
        ],
        "Ext.slider.Toggle":[],
        "Ext.tab.Bar":["widget.tabbar"
        ],
        "Ext.tab.Panel":["widget.tabpanel"
        ],
        "Ext.tab.Tab":["widget.tab"
        ],
        "Ext.table.Cell":["widget.tablecell"
        ],
        "Ext.table.Row":["widget.tablerow"
        ],
        "Ext.table.Table":["widget.table"
        ],
        "Ext.util.AbstractMixedCollection":[],
        "Ext.util.Collection":[],
        "Ext.util.DelayedTask":[],
        "Ext.util.Draggable":[],
        "Ext.util.Filter":[],
        "Ext.util.Format":[],
        "Ext.util.Geolocation":[],
        "Ext.util.Grouper":[],
        "Ext.util.HashMap":[],
        "Ext.util.LineSegment":[],
        "Ext.util.MixedCollection":[],
        "Ext.util.Offset":[],
        "Ext.util.PaintMonitor":[],
        "Ext.util.Point":[],
        "Ext.util.Region":[],
        "Ext.util.SizeMonitor":[],
        "Ext.util.Sortable":[],
        "Ext.util.Sorter":[],
        "Ext.util.TapRepeater":[],
        "Ext.util.Translatable":[],
        "Ext.util.TranslatableGroup":[],
        "Ext.util.Wrapper":[],
        "Ext.util.paintmonitor.Abstract":[],
        "Ext.util.paintmonitor.CssAnimation":[],
        "Ext.util.paintmonitor.OverflowChange":[],
        "Ext.util.sizemonitor.Abstract":[],
        "Ext.util.sizemonitor.OverflowChange":[],
        "Ext.util.sizemonitor.Scroll":[],
        "Ext.util.translatable.Abstract":[],
        "Ext.util.translatable.CssTransform":[],
        "Ext.util.translatable.Dom":[],
        "Ext.util.translatable.ScrollPosition":[],
        "Ext.viewport.Android":[],
        "Ext.viewport.Default":["widget.viewport"
        ],
        "Ext.viewport.Ios":[],
        "Ext.viewport.Viewport":[]
    },
    "alternateToNameMap":{
        "Ext.lib.Component":"Ext.Component",
        "Ext.ComponentMgr":"Ext.ComponentManager",
        "Ext.lib.Container":"Ext.Container",
        "Ext.EventedBase":"Ext.Evented",
        "Ext.lib.Panel":"Ext.Panel",
        "Ext.Carousel":"Ext.carousel.Carousel",
        "Ext.Carousel.Indicator":"Ext.carousel.Indicator",
        "Ext.util.JSONP":"Ext.data.JsonP",
        "Ext.data.Record":"Ext.data.Model",
        "Ext.ModelMgr":"Ext.data.ModelManager",
        "Ext.ModelManager":"Ext.data.ModelManager",
        "Ext.data.Node":"Ext.data.NodeInterface",
        "Ext.StoreMgr":"Ext.data.StoreManager",
        "Ext.data.StoreMgr":"Ext.data.StoreManager",
        "Ext.StoreManager":"Ext.data.StoreManager",
        "Ext.data.validations":"Ext.data.Validations",
        "Ext.data.Association":"Ext.data.association.Association",
        "Ext.data.BelongsToAssociation":"Ext.data.association.BelongsTo",
        "Ext.data.HasManyAssociation":"Ext.data.association.HasMany",
        "Ext.data.HasOneAssociation":"Ext.data.association.HasOne",
        "Ext.data.HttpProxy":"Ext.data.proxy.Ajax",
        "Ext.data.AjaxProxy":"Ext.data.proxy.Ajax",
        "Ext.proxy.ClientProxy":"Ext.data.proxy.Client",
        "Ext.data.DirectProxy":"Ext.data.proxy.Direct",
        "Ext.data.ScriptTagProxy":"Ext.data.proxy.JsonP",
        "Ext.data.LocalStorageProxy":"Ext.data.proxy.LocalStorage",
        "Ext.data.MemoryProxy":"Ext.data.proxy.Memory",
        "Ext.data.DataProxy":"Ext.data.proxy.Proxy",
        "Ext.data.Proxy":"Ext.data.proxy.Proxy",
        "Ext.data.RestProxy":"Ext.data.proxy.Rest",
        "Ext.data.ServerProxy":"Ext.data.proxy.Server",
        "Ext.data.SessionStorageProxy":"Ext.data.proxy.SessionStorage",
        "Ext.data.WebStorageProxy":"Ext.data.proxy.WebStorage",
        "Ext.data.ArrayReader":"Ext.data.reader.Array",
        "Ext.data.JsonReader":"Ext.data.reader.Json",
        "Ext.data.Reader":"Ext.data.reader.Reader",
        "Ext.data.DataReader":"Ext.data.reader.Reader",
        "Ext.data.XmlReader":"Ext.data.reader.Xml",
        "Ext.data.JsonWriter":"Ext.data.writer.Json",
        "Ext.data.DataWriter":"Ext.data.writer.Writer",
        "Ext.data.Writer":"Ext.data.writer.Writer",
        "Ext.data.XmlWriter":"Ext.data.writer.Xml",
        "Ext.DataView":"Ext.dataview.DataView",
        "Ext.IndexBar":"Ext.dataview.IndexBar",
        "Ext.List":"Ext.dataview.List",
        "Ext.NestedList":"Ext.dataview.NestedList",
        "Ext.Direct":"Ext.direct.Manager",
        "Ext.Direct.Transaction":"Ext.direct.Transaction",
        "Ext.CompositeElement":"Ext.dom.CompositeElementLite",
        "Ext.CompositeElementLite":"Ext.dom.CompositeElementLite",
        "Ext.Element":"Ext.dom.Element",
        "Ext.EventObject":"Ext.event.Event",
        "Ext.form.Checkbox":"Ext.field.Checkbox",
        "Ext.form.DatePicker":"Ext.field.DatePicker",
        "Ext.form.Email":"Ext.field.Email",
        "Ext.form.Field":"Ext.field.Field",
        "Ext.form.Hidden":"Ext.field.Hidden",
        "Ext.form.Number":"Ext.field.Number",
        "Ext.form.Password":"Ext.field.Password",
        "Ext.form.Radio":"Ext.field.Radio",
        "Ext.form.Search":"Ext.field.Search",
        "Ext.form.Select":"Ext.field.Select",
        "Ext.form.Slider":"Ext.field.Slider",
        "Ext.form.Spinner":"Ext.field.Spinner",
        "Ext.form.Text":"Ext.field.Text",
        "Ext.form.TextArea":"Ext.field.TextArea",
        "Ext.form.Toggle":"Ext.field.Toggle",
        "Ext.form.Url":"Ext.field.Url",
        "Ext.form.FormPanel":"Ext.form.Panel",
        "Ext.fx.animation.FadeIn":"Ext.fx.animation.Fade",
        "Ext.fx.animation.PopIn":"Ext.fx.animation.Pop",
        "Ext.fx.animation.SlideIn":"Ext.fx.animation.Slide",
        "Ext.util.Observable":"Ext.mixin.Observable",
        "Ext.NavigationView":"Ext.navigation.View",
        "Ext.DatePicker":"Ext.picker.Date",
        "Ext.Picker":"Ext.picker.Picker",
        "Ext.Picker.Slot":"Ext.picker.Slot",
        "Ext.util.Indicator":"Ext.scroll.Indicator",
        "Ext.util.ScrollView":"Ext.scroll.View",
        "Ext.TabBar":"Ext.tab.Bar",
        "Ext.TabPanel":"Ext.tab.Panel",
        "Ext.Tab":"Ext.tab.Tab",
        "Ext.util.GeoLocation":"Ext.util.Geolocation"
    }
};

(function() {
    var scripts = document.getElementsByTagName('script'),
        currentScript = scripts[scripts.length - 1],
        src = currentScript.src,
        path = src.substring(0, src.lastIndexOf('/') + 1),
        Loader = Ext.Loader,
        ClassManager = Ext.ClassManager,
        data = this.ExtBootstrapData,
        nameToAliasesMap = data.nameToAliasesMap,
        alternateToNameMap = data.alternateToNameMap,
        i, ln, name, aliases;

    if (nameToAliasesMap) {
        for (name in nameToAliasesMap) {
            if (nameToAliasesMap.hasOwnProperty(name)) {
                aliases = nameToAliasesMap[name];

                if (aliases.length > 0) {
                    for (i = 0,ln = aliases.length; i < ln; i++) {
                        ClassManager.setAlias(name, aliases[i]);
                    }
                }
                else {
                    ClassManager.setAlias(name, null);
                }
            }
        }
    }

    if (alternateToNameMap) {
        Ext.merge(ClassManager.maps.alternateToName, alternateToNameMap);
    }

    Loader.setConfig({
        enabled: true,
        disableCaching: !/[?&](cache|breakpoint)/i.test(location.search),
        paths: {
            'Ext': path + 'src'
        }
    });

    try {
        delete this.ExtBootstrapData;
    } catch (e) {
        this.ExtBootstrapData = null;
    }
})();

//</debug>

